version: "3.9"
services:
    tosca-database:
        image: postgres
        ports:
            - 5432:5432
        env_file: .env
        environment:
            PGDATA: /var/lib/postgresql/data/pgdata
        volumes:
            - ./.pgdata:/var/lib/postgresql/data
    tosca-backend:
        build: .
        ports:
            - 8080:8080
        env_file: .env
        environment:
            POSTGRES_HOST: tosca-database
        depends_on:
            - tosca-database

